"""
Query Registry for Snowcore Procurement Intelligence
All database queries are registered here for centralized management.
"""

# =============================================================================
# Executive KPI Queries
# =============================================================================

QUERY_EXECUTIVE_KPIS = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_EXECUTIVE_KPIS
"""

QUERY_SPEND_BY_REGION = """
SELECT 
    REGION,
    SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
    COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS PO_COUNT,
    COUNT(DISTINCT SUPPLIER_CODE) AS SUPPLIER_COUNT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
GROUP BY REGION
ORDER BY TOTAL_SPEND DESC
"""

QUERY_SPEND_BY_CATEGORY = """
SELECT 
    MATERIAL_CATEGORY,
    SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
    COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS PO_COUNT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
GROUP BY MATERIAL_CATEGORY
ORDER BY TOTAL_SPEND DESC
"""

QUERY_SPEND_TREND = """
SELECT 
    DATE_TRUNC('month', PURCHASE_ORDER_DATE) AS MONTH,
    SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
    COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS PO_COUNT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
GROUP BY DATE_TRUNC('month', PURCHASE_ORDER_DATE)
ORDER BY MONTH
"""

# =============================================================================
# Supplier Risk Queries
# =============================================================================

QUERY_SUPPLIER_RISK_MAP = """
SELECT 
    SUPPLIER_CODE,
    SUPPLIER_NAME,
    SUPPLIER_COUNTRY,
    REGION,
    LATITUDE,
    LONGITUDE,
    FINANCIAL_HEALTH_SCORE,
    ESG_SCORE,
    RISK_LEVEL,
    TOTAL_SPEND,
    REVENUE_AT_RISK
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_RISK
WHERE LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL
"""

QUERY_HIGH_RISK_SUPPLIERS = """
SELECT 
    SUPPLIER_CODE,
    SUPPLIER_NAME,
    SUPPLIER_COUNTRY,
    REGION,
    FINANCIAL_HEALTH_SCORE,
    CREDIT_RATING,
    ESG_SCORE,
    TOTAL_SPEND,
    REVENUE_AT_RISK,
    RISK_LEVEL
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_RISK
WHERE FINANCIAL_HEALTH_SCORE < 50
ORDER BY REVENUE_AT_RISK DESC
LIMIT 20
"""

QUERY_RISK_DISTRIBUTION = """
SELECT 
    RISK_LEVEL,
    COUNT(*) AS SUPPLIER_COUNT,
    SUM(TOTAL_SPEND) AS TOTAL_SPEND,
    SUM(REVENUE_AT_RISK) AS TOTAL_RISK
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_RISK
GROUP BY RISK_LEVEL
ORDER BY 
    CASE RISK_LEVEL 
        WHEN 'CRITICAL' THEN 1 
        WHEN 'HIGH' THEN 2 
        WHEN 'MEDIUM' THEN 3 
        ELSE 4 
    END
"""

# =============================================================================
# Should-Cost Analysis Queries
# =============================================================================

QUERY_SHOULD_COST_SUMMARY = """
SELECT 
    SHOULD_COST_RECOMMENDATION,
    COUNT(*) AS LINE_COUNT,
    SUM(CONTRACT_TOTAL) AS TOTAL_CONTRACT,
    SUM(POTENTIAL_SAVINGS) AS TOTAL_SAVINGS,
    AVG(PRICE_VARIANCE_PCT) AS AVG_VARIANCE_PCT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SHOULD_COST_ANALYSIS
GROUP BY SHOULD_COST_RECOMMENDATION
ORDER BY TOTAL_SAVINGS DESC
"""

QUERY_SHOULD_COST_BY_CATEGORY = """
SELECT 
    MATERIAL_CATEGORY,
    COUNT(*) AS LINE_COUNT,
    SUM(CONTRACT_TOTAL) AS TOTAL_CONTRACT,
    SUM(POTENTIAL_SAVINGS) AS TOTAL_SAVINGS,
    AVG(CONTRACT_UNIT_PRICE) AS AVG_CONTRACT_PRICE,
    AVG(MARKET_INDEX_PRICE) AS AVG_MARKET_PRICE,
    AVG(PRICE_VARIANCE_PCT) AS AVG_VARIANCE_PCT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SHOULD_COST_ANALYSIS
WHERE MATERIAL_CATEGORY IS NOT NULL
GROUP BY MATERIAL_CATEGORY
ORDER BY TOTAL_SAVINGS DESC
"""

QUERY_PRICE_TREND = """
SELECT 
    DATE_TRUNC('week', PURCHASE_ORDER_DATE) AS WEEK,
    MATERIAL_CATEGORY,
    AVG(CONTRACT_UNIT_PRICE) AS AVG_CONTRACT_PRICE,
    AVG(MARKET_INDEX_PRICE) AS AVG_MARKET_PRICE
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SHOULD_COST_ANALYSIS
WHERE MATERIAL_CATEGORY = :category
GROUP BY DATE_TRUNC('week', PURCHASE_ORDER_DATE), MATERIAL_CATEGORY
ORDER BY WEEK
"""

QUERY_RENEGOTIATE_OPPORTUNITIES = """
SELECT 
    SUPPLIER_NAME,
    PRODUCT_NAME,
    MATERIAL_CATEGORY,
    PURCHASE_ORDER_DATE,
    CONTRACT_UNIT_PRICE,
    MARKET_INDEX_PRICE,
    PRICE_VARIANCE_PCT,
    POTENTIAL_SAVINGS,
    SHOULD_COST_RECOMMENDATION
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SHOULD_COST_ANALYSIS
WHERE SHOULD_COST_RECOMMENDATION = 'RENEGOTIATE'
ORDER BY POTENTIAL_SAVINGS DESC
LIMIT 50
"""

# =============================================================================
# ESG Queries
# =============================================================================

QUERY_ESG_SUMMARY = """
SELECT 
    ESG_RISK_LEVEL,
    COUNT(*) AS SUPPLIER_COUNT,
    AVG(ESG_SCORE) AS AVG_ESG_SCORE,
    AVG(ENVIRONMENTAL_SCORE) AS AVG_ENV_SCORE,
    SUM(TOTAL_SPEND) AS TOTAL_SPEND,
    SUM(SUPPLIER_TOTAL_EMISSIONS_MT) AS TOTAL_EMISSIONS
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_ESG_SUMMARY
GROUP BY ESG_RISK_LEVEL
ORDER BY AVG_ESG_SCORE DESC
"""

QUERY_CARBON_BY_REGION = """
SELECT 
    REGION,
    SUM(SUPPLIER_TOTAL_EMISSIONS_MT) AS TOTAL_EMISSIONS,
    COUNT(DISTINCT SUPPLIER_CODE) AS SUPPLIER_COUNT,
    SUM(TOTAL_SPEND) AS TOTAL_SPEND
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_ESG_SUMMARY
GROUP BY REGION
ORDER BY TOTAL_EMISSIONS DESC
"""

# =============================================================================
# Commodity Index Queries
# =============================================================================

QUERY_COMMODITY_INDICES = """
SELECT 
    INDEX_DATE,
    COMMODITY_TYPE,
    INDEX_VALUE,
    PERCENTAGE_CHANGE_WEEKLY
FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_COMMODITY_INDEX
WHERE INDEX_DATE >= DATEADD(month, -6, CURRENT_DATE())
ORDER BY INDEX_DATE, COMMODITY_TYPE
"""

QUERY_COMMODITY_LATEST = """
SELECT 
    COMMODITY_TYPE,
    INDEX_VALUE,
    PERCENTAGE_CHANGE_DAILY,
    PERCENTAGE_CHANGE_WEEKLY,
    PERCENTAGE_CHANGE_MONTHLY,
    INDEX_DATE
FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_COMMODITY_INDEX
WHERE INDEX_DATE = (SELECT MAX(INDEX_DATE) FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_COMMODITY_INDEX)
ORDER BY COMMODITY_TYPE
"""

# =============================================================================
# Demand Forecasting Queries (Data Scientist Persona)
# =============================================================================

QUERY_DEMAND_FORECAST_PREDICTIONS = """
SELECT 
    MATERIAL_CATEGORY,
    PRODUCT_CODE,
    FORECAST_DATE,
    FORECASTED_DEMAND_QTY,
    ACTUAL_DEMAND_QTY,
    LOWER_BOUND,
    UPPER_BOUND,
    PREDICTION_CONFIDENCE,
    ABS(FORECASTED_DEMAND_QTY - COALESCE(ACTUAL_DEMAND_QTY, FORECASTED_DEMAND_QTY)) AS FORECAST_ERROR
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_DEMAND_FORECAST_PREDICTIONS
WHERE FORECAST_DATE >= DATEADD(day, -90, CURRENT_DATE())
ORDER BY FORECAST_DATE DESC, MATERIAL_CATEGORY
"""

QUERY_FORECAST_ACCURACY_METRICS = """
SELECT 
    MATERIAL_CATEGORY,
    COUNT(*) AS PREDICTION_COUNT,
    AVG(ABS(FORECASTED_DEMAND_QTY - ACTUAL_DEMAND_QTY) / NULLIF(ACTUAL_DEMAND_QTY, 0) * 100) AS MAPE,
    AVG(ABS(FORECASTED_DEMAND_QTY - ACTUAL_DEMAND_QTY)) AS MAE,
    SQRT(AVG(POWER(FORECASTED_DEMAND_QTY - ACTUAL_DEMAND_QTY, 2))) AS RMSE,
    100 - AVG(ABS(FORECASTED_DEMAND_QTY - ACTUAL_DEMAND_QTY) / NULLIF(ACTUAL_DEMAND_QTY, 0) * 100) AS ACCURACY_PCT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_DEMAND_FORECAST_PREDICTIONS
WHERE ACTUAL_DEMAND_QTY IS NOT NULL
GROUP BY MATERIAL_CATEGORY
ORDER BY ACCURACY_PCT DESC
"""

QUERY_FEATURE_IMPORTANCE = """
SELECT 
    FEATURE_NAME,
    IMPORTANCE_SCORE,
    FEATURE_TYPE,
    DESCRIPTION
FROM SNOWCORE_PROCUREMENT.ATOMIC.MODEL_FEATURE_IMPORTANCE
ORDER BY IMPORTANCE_SCORE DESC
"""

QUERY_EXTERNAL_INDICATORS = """
SELECT 
    INDICATOR_NAME,
    INDICATOR_VALUE,
    PERCENTAGE_CHANGE,
    INDICATOR_DATE,
    INDICATOR_TYPE
FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_INDICATORS
WHERE INDICATOR_DATE = (SELECT MAX(INDICATOR_DATE) FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_INDICATORS)
ORDER BY INDICATOR_TYPE, INDICATOR_NAME
"""

QUERY_FORECAST_VS_ACTUAL_TREND = """
SELECT 
    DATE_TRUNC('week', FORECAST_DATE) AS WEEK,
    SUM(FORECASTED_DEMAND_QTY) AS TOTAL_FORECASTED,
    SUM(ACTUAL_DEMAND_QTY) AS TOTAL_ACTUAL
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_DEMAND_FORECAST_PREDICTIONS
WHERE FORECAST_DATE >= DATEADD(month, -3, CURRENT_DATE())
    AND ACTUAL_DEMAND_QTY IS NOT NULL
GROUP BY DATE_TRUNC('week', FORECAST_DATE)
ORDER BY WEEK
"""

# =============================================================================
# Invoice-Level Should-Cost Queries
# =============================================================================

QUERY_INVOICE_DETAILS = """
SELECT 
    PURCHASE_ORDER_NUMBER,
    PURCHASE_ORDER_DATE,
    SUPPLIER_NAME,
    PRODUCT_CODE,
    PRODUCT_NAME,
    MATERIAL_CATEGORY,
    ORDERED_QUANTITY,
    CONTRACT_UNIT_PRICE,
    MARKET_INDEX_PRICE,
    PRICE_VARIANCE,
    PRICE_VARIANCE_PCT,
    POTENTIAL_SAVINGS,
    CONTRACT_TOTAL,
    SHOULD_COST_RECOMMENDATION
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SHOULD_COST_ANALYSIS
WHERE SHOULD_COST_RECOMMENDATION = 'RENEGOTIATE'
ORDER BY POTENTIAL_SAVINGS DESC
LIMIT 100
"""

QUERY_PRICE_TREND_ALL = """
SELECT 
    DATE_TRUNC('week', PURCHASE_ORDER_DATE) AS WEEK,
    MATERIAL_CATEGORY,
    AVG(CONTRACT_UNIT_PRICE) AS AVG_CONTRACT_PRICE,
    AVG(MARKET_INDEX_PRICE) AS AVG_MARKET_PRICE,
    AVG(PRICE_VARIANCE_PCT) AS AVG_VARIANCE_PCT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SHOULD_COST_ANALYSIS
WHERE PURCHASE_ORDER_DATE >= DATEADD(month, -6, CURRENT_DATE())
    AND MATERIAL_CATEGORY IS NOT NULL
GROUP BY DATE_TRUNC('week', PURCHASE_ORDER_DATE), MATERIAL_CATEGORY
ORDER BY WEEK, MATERIAL_CATEGORY
"""

# =============================================================================
# ESG Target Tracking Queries
# =============================================================================

QUERY_ESG_TARGETS = """
SELECT 
    'ESG Score' AS METRIC_NAME,
    AVG(ESG_SCORE) AS CURRENT_VALUE,
    70 AS TARGET_VALUE,
    CASE WHEN AVG(ESG_SCORE) >= 70 THEN 'ON_TRACK' ELSE 'NEEDS_ATTENTION' END AS STATUS
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_ESG_SUMMARY
UNION ALL
SELECT 
    'Carbon Footprint (MT)' AS METRIC_NAME,
    SUM(SUPPLIER_TOTAL_EMISSIONS_MT) AS CURRENT_VALUE,
    50000 AS TARGET_VALUE,
    CASE WHEN SUM(SUPPLIER_TOTAL_EMISSIONS_MT) <= 50000 THEN 'ON_TRACK' ELSE 'NEEDS_ATTENTION' END AS STATUS
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_ESG_SUMMARY
UNION ALL
SELECT 
    'High ESG Risk Suppliers' AS METRIC_NAME,
    COUNT(CASE WHEN ESG_RISK_LEVEL = 'HIGH_RISK' THEN 1 END) AS CURRENT_VALUE,
    10 AS TARGET_VALUE,
    CASE WHEN COUNT(CASE WHEN ESG_RISK_LEVEL = 'HIGH_RISK' THEN 1 END) <= 10 THEN 'ON_TRACK' ELSE 'NEEDS_ATTENTION' END AS STATUS
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_ESG_SUMMARY
"""

QUERY_RISK_ALERTS = """
SELECT 
    'CRITICAL' AS ALERT_TYPE,
    SUPPLIER_NAME,
    SUPPLIER_COUNTRY,
    FINANCIAL_HEALTH_SCORE,
    REVENUE_AT_RISK,
    'Immediate review recommended - financial health critical' AS RECOMMENDATION
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_RISK
WHERE RISK_LEVEL = 'CRITICAL'
ORDER BY REVENUE_AT_RISK DESC
LIMIT 5
"""

# =============================================================================
# Alternative Supplier Recommendations (DRD "Wow" Moment)
# =============================================================================

QUERY_ALTERNATIVE_SUPPLIERS = """
SELECT 
    SUPPLIER_CODE,
    SUPPLIER_NAME,
    SUPPLIER_COUNTRY,
    REGION,
    FINANCIAL_HEALTH_SCORE,
    CREDIT_RATING,
    ESG_SCORE,
    CERTIFICATION_STATUS,
    TOTAL_SPEND,
    RISK_LEVEL,
    'VALIDATED' AS MARKETPLACE_STATUS
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_RISK
WHERE FINANCIAL_HEALTH_SCORE >= 70
    AND ESG_SCORE >= 60
    AND RISK_LEVEL = 'LOW'
ORDER BY FINANCIAL_HEALTH_SCORE DESC, ESG_SCORE DESC
LIMIT 15
"""

# =============================================================================
# Supplier Concentration Analysis
# =============================================================================

QUERY_SPEND_CONCENTRATION = """
WITH supplier_spend AS (
    SELECT 
        SUPPLIER_CODE,
        SUPPLIER_NAME,
        SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
        COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS PO_COUNT,
        COUNT(DISTINCT MATERIAL_CATEGORY) AS CATEGORY_COUNT
    FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
    GROUP BY SUPPLIER_CODE, SUPPLIER_NAME
),
ranked AS (
    SELECT 
        *,
        SUM(TOTAL_SPEND) OVER () AS GRAND_TOTAL,
        ROW_NUMBER() OVER (ORDER BY TOTAL_SPEND DESC) AS RANK
    FROM supplier_spend
)
SELECT 
    SUPPLIER_CODE,
    SUPPLIER_NAME,
    TOTAL_SPEND,
    PO_COUNT,
    CATEGORY_COUNT,
    ROUND(TOTAL_SPEND / GRAND_TOTAL * 100, 2) AS SPEND_PCT,
    SUM(TOTAL_SPEND) OVER (ORDER BY RANK) / GRAND_TOTAL * 100 AS CUMULATIVE_PCT,
    RANK
FROM ranked
ORDER BY RANK
LIMIT 20
"""

QUERY_SINGLE_SOURCE_RISK = """
SELECT 
    MATERIAL_CATEGORY,
    COUNT(DISTINCT SUPPLIER_CODE) AS SUPPLIER_COUNT,
    SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
    LISTAGG(DISTINCT SUPPLIER_NAME, ', ') WITHIN GROUP (ORDER BY SUPPLIER_NAME) AS SUPPLIERS,
    CASE 
        WHEN COUNT(DISTINCT SUPPLIER_CODE) = 1 THEN 'CRITICAL'
        WHEN COUNT(DISTINCT SUPPLIER_CODE) = 2 THEN 'HIGH'
        WHEN COUNT(DISTINCT SUPPLIER_CODE) <= 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS CONCENTRATION_RISK
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
WHERE MATERIAL_CATEGORY IS NOT NULL
GROUP BY MATERIAL_CATEGORY
ORDER BY SUPPLIER_COUNT ASC, TOTAL_SPEND DESC
"""

# =============================================================================
# YoY/QoQ Trending Queries
# =============================================================================

QUERY_SPEND_YOY = """
WITH current_period AS (
    SELECT 
        SUM(SPEND_AMOUNT) AS CURRENT_SPEND,
        COUNT(DISTINCT SUPPLIER_CODE) AS CURRENT_SUPPLIERS,
        COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS CURRENT_POS
    FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
    WHERE PURCHASE_ORDER_DATE >= DATEADD(year, -1, CURRENT_DATE())
),
prior_period AS (
    SELECT 
        SUM(SPEND_AMOUNT) AS PRIOR_SPEND,
        COUNT(DISTINCT SUPPLIER_CODE) AS PRIOR_SUPPLIERS,
        COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS PRIOR_POS
    FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
    WHERE PURCHASE_ORDER_DATE >= DATEADD(year, -2, CURRENT_DATE())
        AND PURCHASE_ORDER_DATE < DATEADD(year, -1, CURRENT_DATE())
)
SELECT 
    c.CURRENT_SPEND,
    p.PRIOR_SPEND,
    ROUND((c.CURRENT_SPEND - p.PRIOR_SPEND) / NULLIF(p.PRIOR_SPEND, 0) * 100, 1) AS SPEND_CHANGE_PCT,
    c.CURRENT_SUPPLIERS,
    p.PRIOR_SUPPLIERS,
    c.CURRENT_SUPPLIERS - p.PRIOR_SUPPLIERS AS SUPPLIER_CHANGE,
    c.CURRENT_POS,
    p.PRIOR_POS,
    ROUND((c.CURRENT_POS - p.PRIOR_POS) / NULLIF(p.PRIOR_POS, 0) * 100, 1) AS PO_CHANGE_PCT
FROM current_period c, prior_period p
"""

QUERY_SPEND_QOQ = """
WITH current_quarter AS (
    SELECT 
        SUM(SPEND_AMOUNT) AS CURRENT_SPEND,
        COUNT(DISTINCT SUPPLIER_CODE) AS CURRENT_SUPPLIERS,
        COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS CURRENT_POS
    FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
    WHERE PURCHASE_ORDER_DATE >= DATE_TRUNC('quarter', CURRENT_DATE())
),
prior_quarter AS (
    SELECT 
        SUM(SPEND_AMOUNT) AS PRIOR_SPEND,
        COUNT(DISTINCT SUPPLIER_CODE) AS PRIOR_SUPPLIERS,
        COUNT(DISTINCT PURCHASE_ORDER_NUMBER) AS PRIOR_POS
    FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
    WHERE PURCHASE_ORDER_DATE >= DATEADD(quarter, -1, DATE_TRUNC('quarter', CURRENT_DATE()))
        AND PURCHASE_ORDER_DATE < DATE_TRUNC('quarter', CURRENT_DATE())
)
SELECT 
    c.CURRENT_SPEND,
    p.PRIOR_SPEND,
    ROUND((c.CURRENT_SPEND - p.PRIOR_SPEND) / NULLIF(p.PRIOR_SPEND, 0) * 100, 1) AS SPEND_CHANGE_PCT,
    c.CURRENT_SUPPLIERS,
    p.PRIOR_SUPPLIERS,
    c.CURRENT_SUPPLIERS - p.PRIOR_SUPPLIERS AS SUPPLIER_CHANGE,
    c.CURRENT_POS,
    p.PRIOR_POS,
    ROUND((c.CURRENT_POS - p.PRIOR_POS) / NULLIF(p.PRIOR_POS, 0) * 100, 1) AS PO_CHANGE_PCT
FROM current_quarter c, prior_quarter p
"""

# =============================================================================
# External Indicator Correlation (Data Scientist)
# =============================================================================

QUERY_INDICATOR_DEMAND_CORRELATION = """
WITH date_range AS (
    SELECT MAX(INDEX_DATE) AS MAX_DATE
    FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_COMMODITY_INDEX
)
SELECT 
    mci.INDEX_DATE,
    mci.COMMODITY_TYPE AS INDICATOR_NAME,
    mci.INDEX_VALUE AS INDICATOR_VALUE,
    COALESCE(da.TOTAL_DEMAND, 0) AS DEMAND_QUANTITY,
    mci.PERCENTAGE_CHANGE_WEEKLY AS INDICATOR_CHANGE
FROM SNOWCORE_PROCUREMENT.ATOMIC.MARKETPLACE_COMMODITY_INDEX mci
CROSS JOIN date_range dr
LEFT JOIN (
    SELECT 
        DATE_TRUNC('week', DEMAND_DATE) AS WEEK,
        SUM(ACTUAL_QUANTITY) AS TOTAL_DEMAND
    FROM SNOWCORE_PROCUREMENT.ATOMIC.DEMAND_ACTUAL
    GROUP BY DATE_TRUNC('week', DEMAND_DATE)
) da ON DATE_TRUNC('week', mci.INDEX_DATE) = da.WEEK
WHERE mci.INDEX_DATE >= DATEADD(month, -6, dr.MAX_DATE)
ORDER BY mci.INDEX_DATE, mci.COMMODITY_TYPE
"""

# =============================================================================
# Division Filtering (Industrial Compression vs BioFlow)
# =============================================================================

QUERY_DIVISIONS = """
SELECT DISTINCT 
    CASE 
        WHEN ERP_SOURCE_SYSTEM LIKE 'BIOFLOW%' THEN 'BioFlow (Life Sciences)'
        ELSE 'Industrial Compression'
    END AS DIVISION
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
ORDER BY DIVISION
"""

# =============================================================================
# Filter/Lookup Queries
# =============================================================================

QUERY_REGIONS = """
SELECT DISTINCT REGION 
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
WHERE REGION IS NOT NULL
ORDER BY REGION
"""

QUERY_CATEGORIES = """
SELECT DISTINCT MATERIAL_CATEGORY 
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
WHERE MATERIAL_CATEGORY IS NOT NULL
ORDER BY MATERIAL_CATEGORY
"""

QUERY_SUPPLIERS = """
SELECT DISTINCT SUPPLIER_CODE, SUPPLIER_NAME 
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
ORDER BY SUPPLIER_NAME
LIMIT 500
"""

QUERY_ERP_SYSTEMS = """
SELECT DISTINCT ERP_SOURCE_SYSTEM 
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SPEND_SUMMARY
ORDER BY ERP_SOURCE_SYSTEM
"""

# =============================================================================
# CPO Persona Queries - Operational Excellence
# =============================================================================

QUERY_OPERATIONAL_KPIS = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_OPERATIONAL_KPIS
"""

QUERY_OTIF_SUMMARY = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_OTIF_SUMMARY
"""

QUERY_OTIF_TREND = """
SELECT 
    MONTH,
    SUM(DELIVERY_COUNT) AS TOTAL_DELIVERIES,
    ROUND(AVG(ON_TIME_RATE), 1) AS ON_TIME_RATE,
    ROUND(AVG(IN_FULL_RATE), 1) AS IN_FULL_RATE,
    ROUND(AVG(OTIF_RATE), 1) AS OTIF_RATE
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_DELIVERY_PERFORMANCE
GROUP BY MONTH
ORDER BY MONTH
"""

QUERY_DELIVERY_BY_SUPPLIER = """
SELECT 
    SUPPLIER_ID,
    SUPPLIER_NAME,
    SUPPLIER_COUNTRY,
    REGION,
    SUM(DELIVERY_COUNT) AS TOTAL_DELIVERIES,
    ROUND(AVG(ON_TIME_RATE), 1) AS ON_TIME_RATE,
    ROUND(AVG(IN_FULL_RATE), 1) AS IN_FULL_RATE,
    ROUND(AVG(OTIF_RATE), 1) AS OTIF_RATE,
    ROUND(AVG(AVG_DAYS_VARIANCE), 1) AS AVG_DAYS_VARIANCE
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_DELIVERY_PERFORMANCE
GROUP BY SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_COUNTRY, REGION
ORDER BY OTIF_RATE DESC
LIMIT 50
"""

QUERY_SCOPE_EMISSIONS_SUMMARY = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SCOPE_EMISSIONS_SUMMARY
"""

QUERY_SCOPE_EMISSIONS_TREND = """
SELECT 
    MONTH,
    SCOPE_TYPE,
    TOTAL_EMISSIONS_MT,
    SUPPLIER_COUNT
FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SCOPE_EMISSIONS
ORDER BY MONTH, SCOPE_TYPE
"""

QUERY_DIVERSITY_SPEND = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_DIVERSITY_SPEND
"""

# =============================================================================
# Category Manager Persona Queries
# =============================================================================

QUERY_SUPPLIER_SCORECARD_LATEST = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_SCORECARD_LATEST
ORDER BY OVERALL_SCORE DESC
LIMIT 50
"""

QUERY_SUPPLIER_SCORECARD_TREND = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_SUPPLIER_SCORECARD_TREND
ORDER BY QUARTER DESC
"""

QUERY_FORWARD_CONTRACT_COVERAGE = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_FORWARD_CONTRACT_COVERAGE
ORDER BY TOTAL_CONTRACT_VALUE DESC
"""

QUERY_CATEGORY_METRICS = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_CATEGORY_METRICS
ORDER BY TOTAL_SPEND DESC
"""

QUERY_LEAD_TIME_VARIABILITY = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_LEAD_TIME_VARIABILITY
ORDER BY LEAD_TIME_STDDEV DESC
LIMIT 30
"""

# =============================================================================
# Data Scientist Persona Queries
# =============================================================================

QUERY_MODEL_REGISTRY = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_MODEL_REGISTRY
"""

QUERY_MODEL_COMPARISON = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_MODEL_COMPARISON
"""

QUERY_EXTERNAL_INDICATORS_LATEST = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_EXTERNAL_INDICATORS_LATEST
"""

QUERY_EXTERNAL_INDICATORS_TREND = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_EXTERNAL_INDICATORS_TREND
"""

QUERY_BUSINESS_IMPACT_SUMMARY = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_BUSINESS_IMPACT_SUMMARY
"""

QUERY_BUSINESS_IMPACT = """
SELECT * FROM SNOWCORE_PROCUREMENT.PROCUREMENT_MART.V_BUSINESS_IMPACT
"""

# =============================================================================
# Query Registry Dictionary
# =============================================================================

QUERY_REGISTRY = {
    # Executive KPIs
    'executive_kpis': QUERY_EXECUTIVE_KPIS,
    'spend_by_region': QUERY_SPEND_BY_REGION,
    'spend_by_category': QUERY_SPEND_BY_CATEGORY,
    'spend_trend': QUERY_SPEND_TREND,
    # Supplier Risk
    'supplier_risk_map': QUERY_SUPPLIER_RISK_MAP,
    'high_risk_suppliers': QUERY_HIGH_RISK_SUPPLIERS,
    'risk_distribution': QUERY_RISK_DISTRIBUTION,
    'risk_alerts': QUERY_RISK_ALERTS,
    # Alternative Suppliers (DRD "Wow" Moment)
    'alternative_suppliers': QUERY_ALTERNATIVE_SUPPLIERS,
    # Should-Cost Analysis
    'should_cost_summary': QUERY_SHOULD_COST_SUMMARY,
    'should_cost_by_category': QUERY_SHOULD_COST_BY_CATEGORY,
    'price_trend': QUERY_PRICE_TREND,
    'price_trend_all': QUERY_PRICE_TREND_ALL,
    'renegotiate_opportunities': QUERY_RENEGOTIATE_OPPORTUNITIES,
    'invoice_details': QUERY_INVOICE_DETAILS,
    # ESG
    'esg_summary': QUERY_ESG_SUMMARY,
    'carbon_by_region': QUERY_CARBON_BY_REGION,
    'esg_targets': QUERY_ESG_TARGETS,
    # Commodity Indices
    'commodity_indices': QUERY_COMMODITY_INDICES,
    'commodity_latest': QUERY_COMMODITY_LATEST,
    # Demand Forecasting (Data Science)
    'demand_forecast_predictions': QUERY_DEMAND_FORECAST_PREDICTIONS,
    'forecast_accuracy_metrics': QUERY_FORECAST_ACCURACY_METRICS,
    'feature_importance': QUERY_FEATURE_IMPORTANCE,
    'external_indicators': QUERY_EXTERNAL_INDICATORS,
    'forecast_vs_actual_trend': QUERY_FORECAST_VS_ACTUAL_TREND,
    # Supplier Concentration Analysis
    'spend_concentration': QUERY_SPEND_CONCENTRATION,
    'single_source_risk': QUERY_SINGLE_SOURCE_RISK,
    # YoY/QoQ Trending
    'spend_yoy': QUERY_SPEND_YOY,
    'spend_qoq': QUERY_SPEND_QOQ,
    # External Indicator Correlation
    'indicator_demand_correlation': QUERY_INDICATOR_DEMAND_CORRELATION,
    # Filters/Lookups
    'regions': QUERY_REGIONS,
    'categories': QUERY_CATEGORIES,
    'suppliers': QUERY_SUPPLIERS,
    'erp_systems': QUERY_ERP_SYSTEMS,
    'divisions': QUERY_DIVISIONS,
    # CPO Persona - Operational Excellence
    'operational_kpis': QUERY_OPERATIONAL_KPIS,
    'otif_summary': QUERY_OTIF_SUMMARY,
    'otif_trend': QUERY_OTIF_TREND,
    'delivery_by_supplier': QUERY_DELIVERY_BY_SUPPLIER,
    'scope_emissions_summary': QUERY_SCOPE_EMISSIONS_SUMMARY,
    'scope_emissions_trend': QUERY_SCOPE_EMISSIONS_TREND,
    'diversity_spend': QUERY_DIVERSITY_SPEND,
    # Category Manager Persona
    'supplier_scorecard_latest': QUERY_SUPPLIER_SCORECARD_LATEST,
    'supplier_scorecard_trend': QUERY_SUPPLIER_SCORECARD_TREND,
    'forward_contract_coverage': QUERY_FORWARD_CONTRACT_COVERAGE,
    'category_metrics': QUERY_CATEGORY_METRICS,
    'lead_time_variability': QUERY_LEAD_TIME_VARIABILITY,
    # Data Scientist Persona
    'model_registry': QUERY_MODEL_REGISTRY,
    'model_comparison': QUERY_MODEL_COMPARISON,
    'external_indicators_latest': QUERY_EXTERNAL_INDICATORS_LATEST,
    'external_indicators_trend': QUERY_EXTERNAL_INDICATORS_TREND,
    'business_impact_summary': QUERY_BUSINESS_IMPACT_SUMMARY,
    'business_impact': QUERY_BUSINESS_IMPACT,
}


def get_query(query_name: str) -> str:
    """Get a registered query by name."""
    if query_name not in QUERY_REGISTRY:
        raise ValueError(f"Query '{query_name}' not found in registry")
    return QUERY_REGISTRY[query_name]
