-- =============================================================================
-- Snowcore Industries Intelligent Sourcing Hub
-- 02_atomic_reference.sql - ATOMIC Layer Reference/Master Tables
-- Conforms to EDM Data Dictionary specifications
-- =============================================================================

USE DATABASE SNOWCORE_PROCUREMENT;
USE SCHEMA ATOMIC;

-- =============================================================================
-- CURRENCY - Currency master
-- =============================================================================
CREATE OR REPLACE TABLE CURRENCY (
    CURRENCY_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    CURRENCY_CODE TEXT(3) NOT NULL UNIQUE,
    CURRENCY_NAME TEXT(100),
    CURRENCY_SYMBOL TEXT(10),
    DECIMAL_PLACES NUMBER(38,0),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- UNIT_OF_MEASURE - Unit of measure master
-- =============================================================================
CREATE OR REPLACE TABLE UNIT_OF_MEASURE (
    UNIT_OF_MEASURE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    UNIT_OF_MEASURE_CODE TEXT(50) NOT NULL UNIQUE,
    UNIT_OF_MEASURE_NAME TEXT(200),
    UNIT_OF_MEASURE_CLASS TEXT(50),
    BASE_UNIT_FLAG BOOLEAN,
    CONVERSION_FACTOR_TO_BASE NUMBER(18,8),
    UNIT_OF_MEASURE_DESCRIPTION TEXT(500),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- GEOGRAPHY - Geographic hierarchy
-- =============================================================================
CREATE OR REPLACE TABLE GEOGRAPHY (
    GEOGRAPHY_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    GEOGRAPHY_CODE TEXT(50) NOT NULL UNIQUE,
    GEOGRAPHY_NAME TEXT(200),
    GEOGRAPHY_TYPE TEXT(50),
    PARENT_GEOGRAPHY_ID NUMBER(38,0) REFERENCES GEOGRAPHY(GEOGRAPHY_ID),
    ISO_COUNTRY_CODE TEXT(3),
    ISO_COUNTRY_CODE_2 TEXT(2),
    ISO_REGION_CODE TEXT(10),
    FIPS_CODE TEXT(10),
    POSTAL_CODE TEXT(20),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PARTY - Base entity for all business parties
-- =============================================================================
CREATE OR REPLACE TABLE PARTY (
    PARTY_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PARTY_CODE TEXT(50) NOT NULL UNIQUE,
    PARTY_TYPE TEXT(50),
    PARTY_NAME TEXT(200),
    TAX_ID TEXT(50),
    DUNS_NUMBER TEXT(13),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PARTY_ADDRESS - Addresses linked to parties
-- =============================================================================
CREATE OR REPLACE TABLE PARTY_ADDRESS (
    PARTY_ADDRESS_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PARTY_ID NUMBER(38,0) REFERENCES PARTY(PARTY_ID),
    ADDRESS_TYPE TEXT(50),
    ADDRESS_LINE_1 TEXT(200),
    ADDRESS_LINE_2 TEXT(200),
    ADDRESS_LINE_3 TEXT(200),
    CITY TEXT(100),
    STATE_PROVINCE TEXT(100),
    POSTAL_CODE TEXT(20),
    COUNTRY TEXT(100),
    GEOGRAPHY_ID NUMBER(38,0) REFERENCES GEOGRAPHY(GEOGRAPHY_ID),
    PRIMARY_ADDRESS_FLAG BOOLEAN,
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- ORGANIZATION - Internal organization hierarchy
-- =============================================================================
CREATE OR REPLACE TABLE ORGANIZATION (
    ORGANIZATION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    ORGANIZATION_CODE TEXT(50) NOT NULL UNIQUE,
    ORGANIZATION_NAME TEXT(200),
    ORGANIZATION_TYPE TEXT(50),
    PARENT_ORGANIZATION_ID NUMBER(38,0) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    ORGANIZATION_LEVEL NUMBER(38,0),
    LEGAL_ENTITY_FLAG BOOLEAN,
    TAX_ID TEXT(50),
    DUNS_NUMBER TEXT(13),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- SITE - Physical locations (plants, warehouses, offices)
-- =============================================================================
CREATE OR REPLACE TABLE SITE (
    SITE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SITE_CODE TEXT(50) NOT NULL UNIQUE,
    SITE_NAME TEXT(200),
    SITE_TYPE TEXT(50),
    ORGANIZATION_ID NUMBER(38,0) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    GEOGRAPHY_ID NUMBER(38,0) REFERENCES GEOGRAPHY(GEOGRAPHY_ID),
    ADDRESS_LINE_1 TEXT(200),
    ADDRESS_LINE_2 TEXT(200),
    CITY TEXT(100),
    STATE_PROVINCE TEXT(100),
    POSTAL_CODE TEXT(20),
    COUNTRY TEXT(100),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    OPERATING_STATUS TEXT(50),
    CAPACITY_METRIC NUMBER(18,4),
    CAPACITY_UNIT_OF_MEASURE TEXT(50),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- LOCATION - Warehouse/storage locations within sites
-- =============================================================================
CREATE OR REPLACE TABLE LOCATION (
    LOCATION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    LOCATION_CODE TEXT(100) NOT NULL UNIQUE,
    LOCATION_NAME TEXT(200),
    LOCATION_TYPE TEXT(50),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    PARENT_LOCATION_ID NUMBER(38,0) REFERENCES LOCATION(LOCATION_ID),
    LOCATION_LEVEL NUMBER(38,0),
    CAPACITY_METRIC NUMBER(18,4),
    CAPACITY_UNIT_OF_MEASURE TEXT(50),
    LENGTH NUMBER(18,4),
    WIDTH NUMBER(18,4),
    HEIGHT NUMBER(18,4),
    DIMENSION_UNIT_OF_MEASURE TEXT(50),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PRODUCT_CATEGORY - Product category hierarchy
-- =============================================================================
CREATE OR REPLACE TABLE PRODUCT_CATEGORY (
    PRODUCT_CATEGORY_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_CATEGORY_CODE TEXT(50) NOT NULL UNIQUE,
    CATEGORY_NAME TEXT(200),
    CATEGORY_DESCRIPTION TEXT(500),
    PARENT_CATEGORY_ID NUMBER(38,0) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID),
    CATEGORY_LEVEL NUMBER(38,0),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PRODUCT - Product/material master
-- =============================================================================
CREATE OR REPLACE TABLE PRODUCT (
    PRODUCT_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_CODE TEXT(100) NOT NULL UNIQUE,
    PRODUCT_NAME TEXT(200),
    PRODUCT_DESCRIPTION_SHORT TEXT(500),
    PRODUCT_DESCRIPTION_LONG TEXT(4000),
    PRODUCT_TYPE TEXT(50),
    PRODUCT_STATUS TEXT(50),
    BASE_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    MAKE_BUY_INDICATOR TEXT(20),
    PRODUCT_CATEGORY_ID NUMBER(38,0) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID),
    OWNING_ORGANIZATION_ID NUMBER(38,0) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PRODUCT_COST - Product standard costs
-- =============================================================================
CREATE OR REPLACE TABLE PRODUCT_COST (
    PRODUCT_COST_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    COST_TYPE TEXT(50),
    MATERIAL_COST NUMBER(18,4),
    LABOR_COST NUMBER(18,4),
    OVERHEAD_COST NUMBER(18,4),
    TOTAL_COST NUMBER(18,4),
    CURRENCY_ID NUMBER(38,0) REFERENCES CURRENCY(CURRENCY_ID),
    COSTING_METHOD TEXT(50),
    EFFECTIVE_DATE DATE,
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PERSON - Person master (for contacts)
-- =============================================================================
CREATE OR REPLACE TABLE PERSON (
    PERSON_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PARTY_ID NUMBER(38,0) REFERENCES PARTY(PARTY_ID),
    FIRST_NAME TEXT(100),
    LAST_NAME TEXT(100),
    EMAIL TEXT(200),
    PHONE TEXT(50),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- Success message
SELECT 'ATOMIC reference tables created successfully' AS status;
