-- =============================================================================
-- Snowcore Industries Intelligent Sourcing Hub
-- 03_atomic_procurement.sql - ATOMIC Layer Procurement & Supplier Tables
-- Conforms to EDM Data Dictionary specifications + new demo-specific entities
-- =============================================================================

USE DATABASE SNOWCORE_PROCUREMENT;
USE SCHEMA ATOMIC;

-- =============================================================================
-- SUPPLIER - Supplier master
-- =============================================================================
CREATE OR REPLACE TABLE SUPPLIER (
    SUPPLIER_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_CODE TEXT(50) NOT NULL UNIQUE,
    PARTY_ID NUMBER(38,0) REFERENCES PARTY(PARTY_ID),
    SUPPLIER_STATUS TEXT(50),
    SUPPLIER_TYPE TEXT(50),
    SUPPLIER_CLASS TEXT(50),
    APPROVAL_DATE DATE,
    PRIMARY_CONTACT_PERSON_ID NUMBER(38,0) REFERENCES PERSON(PERSON_ID),
    PAYMENT_TERMS TEXT(100),
    CURRENCY_ID NUMBER(38,0) REFERENCES CURRENCY(CURRENCY_ID),
    TAX_IDENTIFICATION_NUMBER TEXT(50),
    DUNS_NUMBER TEXT(13),
    CERTIFICATION_STATUS TEXT(200),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- SUPPLIER_SITE - Supplier locations
-- =============================================================================
CREATE OR REPLACE TABLE SUPPLIER_SITE (
    SUPPLIER_SITE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    SITE_CODE TEXT(50) NOT NULL,
    SITE_NAME TEXT(200),
    PARTY_ADDRESS_ID NUMBER(38,0) REFERENCES PARTY_ADDRESS(PARTY_ADDRESS_ID),
    PRIMARY_CONTACT_AT_SITE TEXT(200),
    SITE_CAPABILITIES TEXT(1000),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- SUPPLIER_PRODUCT - Supplier-product catalog (prices, lead times)
-- =============================================================================
CREATE OR REPLACE TABLE SUPPLIER_PRODUCT (
    SUPPLIER_PRODUCT_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SUPPLIER_PART_NUMBER TEXT(100),
    SUPPLIER_PRODUCT_DESCRIPTION TEXT(500),
    LEAD_TIME_DAYS NUMBER(38,0),
    MINIMUM_ORDER_QUANTITY NUMBER(18,4),
    ORDER_MULTIPLE NUMBER(18,4),
    UNIT_PRICE NUMBER(18,4),
    PRICE_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    CURRENCY_ID NUMBER(38,0) REFERENCES CURRENCY(CURRENCY_ID),
    PREFERRED_SUPPLIER_FLAG BOOLEAN,
    EFFECTIVE_DATE DATE,
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- SUPPLIER_PERFORMANCE - KPI metrics for suppliers
-- =============================================================================
CREATE OR REPLACE TABLE SUPPLIER_PERFORMANCE (
    SUPPLIER_PERFORMANCE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    EVALUATION_PERIOD TEXT(50),
    METRIC_TYPE TEXT(50),
    METRIC_VALUE NUMBER(18,4),
    TARGET_VALUE NUMBER(18,4),
    RATING TEXT(50),
    COMMENTS TEXT(2000),
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PURCHASE_REQUISITION - Purchase requisition header
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_REQUISITION (
    PURCHASE_REQUISITION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    REQUISITION_NUMBER TEXT(100) NOT NULL UNIQUE,
    REQUISITION_DATE DATE,
    REQUESTER_EMPLOYEE_ID NUMBER(38,0),
    REQUESTING_ORGANIZATION_ID NUMBER(38,0) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    REQUISITION_TYPE TEXT(50),
    REQUISITION_STATUS TEXT(50),
    PRIORITY TEXT(50),
    JUSTIFICATION TEXT(2000),
    NOTES TEXT(4000),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PURCHASE_REQUISITION_LINE - Purchase requisition line items
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_REQUISITION_LINE (
    PURCHASE_REQUISITION_LINE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PURCHASE_REQUISITION_ID NUMBER(38,0) REFERENCES PURCHASE_REQUISITION(PURCHASE_REQUISITION_ID),
    LINE_NUMBER NUMBER(38,0),
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    ITEM_DESCRIPTION TEXT(500),
    REQUESTED_QUANTITY NUMBER(18,4),
    REQUESTED_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    NEED_BY_DATE DATE,
    ESTIMATED_UNIT_PRICE NUMBER(18,4),
    ESTIMATED_TOTAL NUMBER(18,2),
    SUGGESTED_SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    GENERAL_LEDGER_ACCOUNT_CODE TEXT(50),
    LINE_STATUS TEXT(50)
);

-- =============================================================================
-- PURCHASE_ORDER - Purchase order header
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_ORDER (
    PURCHASE_ORDER_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PURCHASE_ORDER_NUMBER TEXT(100) NOT NULL UNIQUE,
    PURCHASE_ORDER_DATE DATE,
    REVISION_NUMBER NUMBER(38,0),
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    SUPPLIER_SITE_ID NUMBER(38,0) REFERENCES SUPPLIER_SITE(SUPPLIER_SITE_ID),
    BUYER_EMPLOYEE_ID NUMBER(38,0),
    PURCHASE_ORDER_TYPE TEXT(50),
    PURCHASE_ORDER_STATUS TEXT(50),
    CURRENCY_ID NUMBER(38,0) REFERENCES CURRENCY(CURRENCY_ID),
    PAYMENT_TERMS TEXT(100),
    SHIPPING_TERMS TEXT(100),
    SHIP_TO_SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    SHIP_TO_LOCATION_ID NUMBER(38,0) REFERENCES LOCATION(LOCATION_ID),
    BILL_TO_ORGANIZATION_ID NUMBER(38,0) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    TOTAL_PURCHASE_ORDER_VALUE NUMBER(18,2),
    VENDOR_REFERENCE_NUMBER TEXT(100),
    ERP_SOURCE_SYSTEM TEXT(50),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PURCHASE_ORDER_LINE - Purchase order line items
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_ORDER_LINE (
    PURCHASE_ORDER_LINE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PURCHASE_ORDER_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER(PURCHASE_ORDER_ID),
    LINE_NUMBER NUMBER(38,0),
    PURCHASE_REQUISITION_LINE_ID NUMBER(38,0) REFERENCES PURCHASE_REQUISITION_LINE(PURCHASE_REQUISITION_LINE_ID),
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    ITEM_DESCRIPTION TEXT(500),
    SUPPLIER_PART_NUMBER TEXT(100),
    ORDERED_QUANTITY NUMBER(18,4),
    ORDERED_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    UNIT_PRICE NUMBER(18,4),
    EXTENDED_PRICE NUMBER(18,2),
    NEED_BY_DATE DATE,
    PROMISED_DELIVERY_DATE DATE,
    LINE_STATUS TEXT(50),
    RECEIVED_QUANTITY NUMBER(18,4),
    INVOICED_QUANTITY NUMBER(18,4),
    TAX_CODE TEXT(50),
    TAX_AMOUNT NUMBER(18,2),
    GENERAL_LEDGER_ACCOUNT_CODE TEXT(50)
);

-- =============================================================================
-- PURCHASE_ORDER_RECEIPT - Receipt header
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_ORDER_RECEIPT (
    PURCHASE_ORDER_RECEIPT_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    RECEIPT_NUMBER TEXT(100) NOT NULL UNIQUE,
    RECEIPT_DATE DATE,
    RECEIPT_TIMESTAMP TIMESTAMP_NTZ,
    PURCHASE_ORDER_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER(PURCHASE_ORDER_ID),
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    RECEIVING_SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    PACKING_SLIP_NUMBER TEXT(100),
    BILL_OF_LADING_NUMBER TEXT(100),
    CARRIER_PARTY_ID NUMBER(38,0) REFERENCES PARTY(PARTY_ID),
    RECEIPT_STATUS TEXT(50)
);

-- =============================================================================
-- PURCHASE_ORDER_RECEIPT_LINE - Receipt line items
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_ORDER_RECEIPT_LINE (
    PURCHASE_ORDER_RECEIPT_LINE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PURCHASE_ORDER_RECEIPT_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER_RECEIPT(PURCHASE_ORDER_RECEIPT_ID),
    LINE_NUMBER NUMBER(38,0),
    PURCHASE_ORDER_LINE_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER_LINE(PURCHASE_ORDER_LINE_ID),
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    RECEIVED_QUANTITY NUMBER(18,4),
    RECEIVED_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    ACCEPTED_QUANTITY NUMBER(18,4),
    REJECTED_QUANTITY NUMBER(18,4),
    LOT_NUMBER TEXT(100),
    SERIAL_NUMBERS TEXT(4000),
    TO_LOCATION_ID NUMBER(38,0) REFERENCES LOCATION(LOCATION_ID),
    RECEIVER_EMPLOYEE_ID NUMBER(38,0),
    QUALITY_INSPECTION_REQUIRED_FLAG BOOLEAN
);

-- =============================================================================
-- PURCHASE_ORDER_INVOICE - Invoice header
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_ORDER_INVOICE (
    PURCHASE_ORDER_INVOICE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    VENDOR_INVOICE_NUMBER TEXT(100) NOT NULL,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    PURCHASE_ORDER_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER(PURCHASE_ORDER_ID),
    INVOICE_CURRENCY_ID NUMBER(38,0) REFERENCES CURRENCY(CURRENCY_ID),
    INVOICE_AMOUNT NUMBER(18,2),
    TAX_AMOUNT NUMBER(18,2),
    FREIGHT_AMOUNT NUMBER(18,2),
    TOTAL_AMOUNT NUMBER(18,2),
    PAYMENT_TERMS TEXT(100),
    INVOICE_STATUS TEXT(50),
    PAYMENT_DATE DATE,
    PAYMENT_REFERENCE TEXT(100)
);

-- =============================================================================
-- PURCHASE_ORDER_INVOICE_LINE - Invoice line items
-- =============================================================================
CREATE OR REPLACE TABLE PURCHASE_ORDER_INVOICE_LINE (
    PURCHASE_ORDER_INVOICE_LINE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PURCHASE_ORDER_INVOICE_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER_INVOICE(PURCHASE_ORDER_INVOICE_ID),
    LINE_NUMBER NUMBER(38,0),
    PURCHASE_ORDER_LINE_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER_LINE(PURCHASE_ORDER_LINE_ID),
    PURCHASE_ORDER_RECEIPT_LINE_ID NUMBER(38,0) REFERENCES PURCHASE_ORDER_RECEIPT_LINE(PURCHASE_ORDER_RECEIPT_LINE_ID),
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    INVOICED_QUANTITY NUMBER(18,4),
    INVOICED_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    UNIT_PRICE NUMBER(18,4),
    EXTENDED_AMOUNT NUMBER(18,2),
    TAX_AMOUNT NUMBER(18,2),
    DISCOUNT_AMOUNT NUMBER(18,2),
    MATCH_STATUS TEXT(50)
);

-- =============================================================================
-- INVENTORY_ITEM - Item-site planning parameters
-- =============================================================================
CREATE OR REPLACE TABLE INVENTORY_ITEM (
    INVENTORY_ITEM_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    ITEM_TYPE TEXT(50),
    STOCKING_TYPE TEXT(50),
    PLANNING_METHOD TEXT(50),
    REPLENISHMENT_LEAD_TIME NUMBER(38,0),
    SAFETY_STOCK_QUANTITY NUMBER(18,4),
    REORDER_POINT NUMBER(18,4),
    ORDER_QUANTITY NUMBER(18,4),
    ABC_CLASS TEXT(10),
    CYCLE_COUNT_FREQUENCY NUMBER(38,0),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- INVENTORY_BALANCE - Current inventory on-hand
-- =============================================================================
CREATE OR REPLACE TABLE INVENTORY_BALANCE (
    INVENTORY_BALANCE_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    LOCATION_ID NUMBER(38,0) REFERENCES LOCATION(LOCATION_ID),
    LOT_ID NUMBER(38,0),
    INVENTORY_STATUS TEXT(50),
    QUANTITY_ON_HAND NUMBER(18,4),
    UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    LAST_TRANSACTION_DATE TIMESTAMP_NTZ
);

-- =============================================================================
-- DEMAND_FORECAST - Demand forecasts
-- =============================================================================
CREATE OR REPLACE TABLE DEMAND_FORECAST (
    DEMAND_FORECAST_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    CUSTOMER_ID NUMBER(38,0),
    FORECAST_DATE DATE,
    FORECAST_CREATION_DATE DATE,
    FORECAST_QUANTITY NUMBER(18,4),
    FORECAST_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    FORECAST_TYPE TEXT(50),
    FORECAST_METHOD TEXT(50),
    FORECAST_HORIZON TEXT(50),
    CONFIDENCE_LEVEL NUMBER(5,2),
    FORECAST_VERSION_SCENARIO TEXT(50),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- DEMAND_ACTUAL - Actual consumption/demand
-- =============================================================================
CREATE OR REPLACE TABLE DEMAND_ACTUAL (
    DEMAND_ACTUAL_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    DEMAND_DATE DATE,
    ACTUAL_QUANTITY NUMBER(18,4),
    ACTUAL_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    DEMAND_SOURCE TEXT(50)
);

-- =============================================================================
-- EMISSION_RECORD - Carbon emissions tracking (ESG)
-- =============================================================================
CREATE OR REPLACE TABLE EMISSION_RECORD (
    EMISSION_RECORD_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    RECORD_DATE DATE,
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    EMISSION_SOURCE TEXT(100),
    POLLUTANT_NAME TEXT(100),
    EMISSION_QUANTITY NUMBER(18,4),
    EMISSION_UNIT_OF_MEASURE_ID NUMBER(38,0) REFERENCES UNIT_OF_MEASURE(UNIT_OF_MEASURE_ID),
    PERMIT_LIMIT NUMBER(18,4),
    IS_WITHIN_PERMIT_LIMIT_FLAG BOOLEAN,
    MEASUREMENT_METHOD TEXT(50)
);

-- =============================================================================
-- NEW DEMO-SPECIFIC ENTITIES (not in EDM)
-- =============================================================================

-- =============================================================================
-- MARKETPLACE_COMMODITY_INDEX - External commodity price indices
-- =============================================================================
CREATE OR REPLACE TABLE MARKETPLACE_COMMODITY_INDEX (
    INDEX_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    INDEX_DATE DATE NOT NULL,
    COMMODITY_TYPE TEXT(100) NOT NULL,
    COMMODITY_NAME TEXT(200),
    INDEX_VALUE NUMBER(18,4),
    INDEX_UNIT TEXT(50),
    CURRENCY_ID NUMBER(38,0) REFERENCES CURRENCY(CURRENCY_ID),
    PERCENTAGE_CHANGE_DAILY NUMBER(8,4),
    PERCENTAGE_CHANGE_WEEKLY NUMBER(8,4),
    PERCENTAGE_CHANGE_MONTHLY NUMBER(8,4),
    DATA_SOURCE TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- MARKETPLACE_SUPPLIER_RISK - External supplier risk scores
-- =============================================================================
CREATE OR REPLACE TABLE MARKETPLACE_SUPPLIER_RISK (
    RISK_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    ASSESSMENT_DATE DATE NOT NULL,
    FINANCIAL_HEALTH_SCORE NUMBER(5,2),
    CREDIT_RATING TEXT(10),
    BANKRUPTCY_PROBABILITY NUMBER(8,6),
    GEOPOLITICAL_RISK_LEVEL TEXT(20),
    GEOPOLITICAL_RISK_SCORE NUMBER(5,2),
    ESG_SCORE NUMBER(5,2),
    ENVIRONMENTAL_SCORE NUMBER(5,2),
    SOCIAL_SCORE NUMBER(5,2),
    GOVERNANCE_SCORE NUMBER(5,2),
    CYBER_RISK_SCORE NUMBER(5,2),
    SUPPLY_CHAIN_RISK_SCORE NUMBER(5,2),
    OVERALL_RISK_RATING TEXT(20),
    DATA_SOURCE TEXT(100),
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ,
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- SUPPLIER_DOCUMENT - Unstructured documents for Cortex Search RAG
-- =============================================================================
CREATE OR REPLACE TABLE SUPPLIER_DOCUMENT (
    DOCUMENT_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_ID NUMBER(38,0) REFERENCES SUPPLIER(SUPPLIER_ID),
    DOCUMENT_TYPE TEXT(50),
    DOCUMENT_TITLE TEXT(500),
    DOCUMENT_CONTENT TEXT,
    DOCUMENT_SUMMARY TEXT(2000),
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    DOCUMENT_STATUS TEXT(50),
    FILE_PATH TEXT(500),
    FILE_SIZE_BYTES NUMBER(38,0),
    CREATED_BY_USER TEXT(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER TEXT(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- DEMAND_FORECAST_PREDICTIONS - ML model output table
-- =============================================================================
CREATE OR REPLACE TABLE DEMAND_FORECAST_PREDICTIONS (
    PREDICTION_ID NUMBER(38,0) NOT NULL PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID NUMBER(38,0) REFERENCES PRODUCT(PRODUCT_ID),
    SITE_ID NUMBER(38,0) REFERENCES SITE(SITE_ID),
    PREDICTION_DATE DATE,
    FORECASTED_MATERIAL_DEMAND_QTY NUMBER(18,4),
    PREDICTION_LOWER_BOUND NUMBER(18,4),
    PREDICTION_UPPER_BOUND NUMBER(18,4),
    CONFIDENCE_LEVEL NUMBER(5,2),
    MODEL_VERSION TEXT(50),
    FEATURE_IMPORTANCE VARIANT,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- MODEL_FEATURE_IMPORTANCE - ML model feature importance scores
-- =============================================================================
CREATE OR REPLACE TABLE MODEL_FEATURE_IMPORTANCE (
    FEATURE_IMPORTANCE_ID NUMBER(38,0) NOT NULL PRIMARY KEY AUTOINCREMENT,
    MODEL_VERSION TEXT(50) NOT NULL,
    FEATURE_NAME TEXT(200) NOT NULL,
    IMPORTANCE_SCORE NUMBER(10,6),
    FEATURE_TYPE TEXT(50),  -- 'Internal', 'External', 'Derived'
    DESCRIPTION TEXT(500),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Success message
SELECT 'ATOMIC procurement tables created successfully' AS status;
