-- =============================================================================
-- Snowcore Industries Intelligent Sourcing Hub
-- 04_raw_layer.sql - RAW Layer Tables for ERP and Marketplace Ingestion
-- =============================================================================

USE DATABASE SNOWCORE_PROCUREMENT;
USE SCHEMA RAW;

-- =============================================================================
-- RAW ERP TABLES - Simulating 50+ legacy ERP sources
-- =============================================================================

-- SAP ERP Source
CREATE OR REPLACE TABLE RAW_PO_SAP (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    EBELN TEXT(100),           -- PO Number
    EBELP NUMBER(38,0),        -- PO Line
    LIFNR TEXT(50),            -- Vendor Number
    MATNR TEXT(50),            -- Material Number
    MENGE NUMBER(18,4),        -- Quantity
    MEINS TEXT(10),            -- UOM
    NETPR NUMBER(18,4),        -- Net Price
    WAERS TEXT(3),             -- Currency
    AEDAT DATE,                -- Change Date
    ERDAT DATE,                -- Created Date
    BUKRS TEXT(10),            -- Company Code
    WERKS TEXT(10),            -- Plant
    SOURCE_SYSTEM TEXT(50) DEFAULT 'SAP',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Oracle ERP Source
CREATE OR REPLACE TABLE RAW_PO_ORACLE (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    PO_HEADER_ID NUMBER(38,0),
    PO_LINE_ID NUMBER(38,0),
    PO_NUMBER TEXT(100),
    LINE_NUM NUMBER(38,0),
    VENDOR_ID NUMBER(38,0),
    VENDOR_NAME TEXT(200),
    ITEM_ID NUMBER(38,0),
    ITEM_DESCRIPTION TEXT(500),
    QUANTITY NUMBER(18,4),
    UNIT_PRICE NUMBER(18,4),
    CURRENCY_CODE TEXT(3),
    CREATION_DATE DATE,
    LAST_UPDATE_DATE DATE,
    ORG_ID NUMBER(38,0),
    SHIP_TO_LOCATION_ID NUMBER(38,0),
    SOURCE_SYSTEM TEXT(50) DEFAULT 'ORACLE',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- BioFlow Division (Life Sciences - Proprietary ERP)
CREATE OR REPLACE TABLE RAW_PO_BIOFLOW (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    ORDER_REF TEXT(100),
    ORDER_LINE NUMBER(38,0),
    SUPPLIER_CODE TEXT(50),
    SUPPLIER_NAME TEXT(200),
    PRODUCT_SKU TEXT(50),
    PRODUCT_DESC TEXT(500),
    QTY_ORDERED NUMBER(18,4),
    UNIT_COST NUMBER(18,4),
    CURRENCY TEXT(3),
    ORDER_DATE DATE,
    DELIVERY_DATE DATE,
    FACILITY_CODE TEXT(20),
    REGULATORY_CLASS TEXT(50),
    GMP_COMPLIANT BOOLEAN,
    SOURCE_SYSTEM TEXT(50) DEFAULT 'BIOFLOW',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Generic Multi-ERP Staging Table (for the other 47+ ERPs)
CREATE OR REPLACE TABLE RAW_PO_GENERIC (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    SOURCE_SYSTEM TEXT(50) NOT NULL,
    SOURCE_PO_NUMBER TEXT(100),
    SOURCE_LINE_NUMBER NUMBER(38,0),
    SOURCE_SUPPLIER_ID TEXT(100),
    SOURCE_SUPPLIER_NAME TEXT(200),
    SOURCE_PRODUCT_ID TEXT(100),
    SOURCE_PRODUCT_DESC TEXT(500),
    QUANTITY NUMBER(18,4),
    UNIT_PRICE NUMBER(18,4),
    EXTENDED_PRICE NUMBER(18,2),
    CURRENCY_CODE TEXT(3),
    ORDER_DATE DATE,
    DELIVERY_DATE DATE,
    SITE_CODE TEXT(50),
    DIVISION TEXT(50),
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- RAW MARKETPLACE TABLES - External data feeds
-- =============================================================================

-- Marketplace Risk Data (e.g., D&B, Moody's)
CREATE OR REPLACE TABLE RAW_MARKETPLACE_RISK (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    DATA_PROVIDER TEXT(100),
    ASSESSMENT_DATE DATE,
    DUNS_NUMBER TEXT(13),
    COMPANY_NAME TEXT(200),
    FINANCIAL_HEALTH_SCORE NUMBER(5,2),
    CREDIT_RATING TEXT(10),
    BANKRUPTCY_PROBABILITY NUMBER(8,6),
    PAYMENT_INDEX NUMBER(5,2),
    GEOPOLITICAL_RISK_COUNTRY TEXT(100),
    GEOPOLITICAL_RISK_SCORE NUMBER(5,2),
    CYBER_RISK_SCORE NUMBER(5,2),
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Marketplace Commodities Data (e.g., LME, COMEX)
CREATE OR REPLACE TABLE RAW_MARKETPLACE_COMMODITIES (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    DATA_PROVIDER TEXT(100),
    PRICE_DATE DATE,
    COMMODITY_SYMBOL TEXT(20),
    COMMODITY_NAME TEXT(100),
    SPOT_PRICE NUMBER(18,4),
    FORWARD_1M NUMBER(18,4),
    FORWARD_3M NUMBER(18,4),
    CURRENCY TEXT(3),
    PRICE_UNIT TEXT(50),
    DAILY_CHANGE_PCT NUMBER(8,4),
    VOLUME NUMBER(18,0),
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Marketplace ESG Data (e.g., MSCI, Sustainalytics)
CREATE OR REPLACE TABLE RAW_MARKETPLACE_ESG (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    DATA_PROVIDER TEXT(100),
    RATING_DATE DATE,
    COMPANY_ID TEXT(50),
    COMPANY_NAME TEXT(200),
    ESG_OVERALL_SCORE NUMBER(5,2),
    ENVIRONMENTAL_SCORE NUMBER(5,2),
    SOCIAL_SCORE NUMBER(5,2),
    GOVERNANCE_SCORE NUMBER(5,2),
    CARBON_INTENSITY NUMBER(18,4),
    CARBON_INTENSITY_UNIT TEXT(50),
    CONTROVERSY_FLAG BOOLEAN,
    CONTROVERSY_DETAILS TEXT(2000),
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- External Economic Indicators (Construction starts, Pharma R&D)
CREATE OR REPLACE TABLE RAW_MARKETPLACE_INDICATORS (
    RAW_ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    DATA_PROVIDER TEXT(100),
    INDICATOR_DATE DATE,
    INDICATOR_NAME TEXT(200),
    INDICATOR_CATEGORY TEXT(100),
    INDICATOR_VALUE NUMBER(18,4),
    INDICATOR_UNIT TEXT(50),
    REGION TEXT(50),
    COUNTRY TEXT(100),
    YEAR_OVER_YEAR_CHANGE_PCT NUMBER(8,4),
    SEASONALLY_ADJUSTED_FLAG BOOLEAN,
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Success message
SELECT 'RAW layer tables created successfully' AS status;
