-- =============================================================================
-- Snowcore Industries Intelligent Sourcing Hub
-- 05_mart_layer.sql - PROCUREMENT_MART Aggregated Views
-- =============================================================================

USE DATABASE SNOWCORE_PROCUREMENT;
USE SCHEMA PROCUREMENT_MART;

-- =============================================================================
-- V_SPEND_SUMMARY - Consolidated spend analytics
-- =============================================================================
CREATE OR REPLACE VIEW V_SPEND_SUMMARY AS
SELECT 
    po.PURCHASE_ORDER_ID,
    po.PURCHASE_ORDER_NUMBER,
    po.PURCHASE_ORDER_DATE,
    po.ERP_SOURCE_SYSTEM,
    s.SUPPLIER_ID,
    s.SUPPLIER_CODE,
    p.PARTY_NAME AS SUPPLIER_NAME,
    s.SUPPLIER_TYPE,
    s.SUPPLIER_CLASS,
    pa.CITY AS SUPPLIER_CITY,
    pa.STATE_PROVINCE AS SUPPLIER_STATE,
    pa.COUNTRY AS SUPPLIER_COUNTRY,
    g.GEOGRAPHY_NAME AS REGION,
    pol.PRODUCT_ID,
    prod.PRODUCT_CODE,
    prod.PRODUCT_NAME,
    pc.CATEGORY_NAME AS MATERIAL_CATEGORY,
    pc.PRODUCT_CATEGORY_CODE AS CATEGORY_CODE,
    pol.ORDERED_QUANTITY,
    pol.UNIT_PRICE,
    pol.EXTENDED_PRICE AS SPEND_AMOUNT,
    cur.CURRENCY_CODE,
    pol.NEED_BY_DATE,
    pol.PROMISED_DELIVERY_DATE,
    pol.LINE_STATUS,
    org.ORGANIZATION_NAME AS BUYING_ORGANIZATION,
    site.SITE_NAME AS SHIP_TO_SITE,
    site.COUNTRY AS SHIP_TO_COUNTRY
FROM ATOMIC.PURCHASE_ORDER po
JOIN ATOMIC.PURCHASE_ORDER_LINE pol ON po.PURCHASE_ORDER_ID = pol.PURCHASE_ORDER_ID
JOIN ATOMIC.SUPPLIER s ON po.SUPPLIER_ID = s.SUPPLIER_ID
JOIN ATOMIC.PARTY p ON s.PARTY_ID = p.PARTY_ID
LEFT JOIN ATOMIC.PARTY_ADDRESS pa ON p.PARTY_ID = pa.PARTY_ID AND pa.PRIMARY_ADDRESS_FLAG = TRUE
LEFT JOIN ATOMIC.GEOGRAPHY g ON pa.GEOGRAPHY_ID = g.GEOGRAPHY_ID
LEFT JOIN ATOMIC.PRODUCT prod ON pol.PRODUCT_ID = prod.PRODUCT_ID
LEFT JOIN ATOMIC.PRODUCT_CATEGORY pc ON prod.PRODUCT_CATEGORY_ID = pc.PRODUCT_CATEGORY_ID
LEFT JOIN ATOMIC.CURRENCY cur ON po.CURRENCY_ID = cur.CURRENCY_ID
LEFT JOIN ATOMIC.ORGANIZATION org ON po.BILL_TO_ORGANIZATION_ID = org.ORGANIZATION_ID
LEFT JOIN ATOMIC.SITE site ON po.SHIP_TO_SITE_ID = site.SITE_ID
WHERE po.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- V_SUPPLIER_RISK - Supplier risk with financial health
-- =============================================================================
CREATE OR REPLACE VIEW V_SUPPLIER_RISK AS
SELECT 
    s.SUPPLIER_ID,
    s.SUPPLIER_CODE,
    p.PARTY_NAME AS SUPPLIER_NAME,
    s.SUPPLIER_TYPE,
    s.SUPPLIER_CLASS,
    s.CERTIFICATION_STATUS,
    pa.CITY AS SUPPLIER_CITY,
    pa.STATE_PROVINCE AS SUPPLIER_STATE,
    pa.COUNTRY AS SUPPLIER_COUNTRY,
    pa.LATITUDE,
    pa.LONGITUDE,
    g.GEOGRAPHY_NAME AS REGION,
    g.ISO_COUNTRY_CODE,
    msr.ASSESSMENT_DATE,
    msr.FINANCIAL_HEALTH_SCORE,
    msr.CREDIT_RATING,
    msr.BANKRUPTCY_PROBABILITY,
    msr.GEOPOLITICAL_RISK_LEVEL,
    msr.GEOPOLITICAL_RISK_SCORE,
    msr.ESG_SCORE,
    msr.ENVIRONMENTAL_SCORE,
    msr.SOCIAL_SCORE,
    msr.GOVERNANCE_SCORE,
    msr.CYBER_RISK_SCORE,
    msr.SUPPLY_CHAIN_RISK_SCORE,
    msr.OVERALL_RISK_RATING,
    -- Calculate risk exposure
    COALESCE(spend.TOTAL_SPEND, 0) AS TOTAL_SPEND,
    COALESCE(spend.PO_COUNT, 0) AS PO_COUNT,
    CASE 
        WHEN msr.FINANCIAL_HEALTH_SCORE < 30 THEN 'CRITICAL'
        WHEN msr.FINANCIAL_HEALTH_SCORE < 50 THEN 'HIGH'
        WHEN msr.FINANCIAL_HEALTH_SCORE < 70 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL,
    CASE 
        WHEN msr.FINANCIAL_HEALTH_SCORE < 50 
        THEN COALESCE(spend.TOTAL_SPEND, 0) 
        ELSE 0 
    END AS REVENUE_AT_RISK
FROM ATOMIC.SUPPLIER s
JOIN ATOMIC.PARTY p ON s.PARTY_ID = p.PARTY_ID
LEFT JOIN ATOMIC.PARTY_ADDRESS pa ON p.PARTY_ID = pa.PARTY_ID AND pa.PRIMARY_ADDRESS_FLAG = TRUE
LEFT JOIN ATOMIC.GEOGRAPHY g ON pa.GEOGRAPHY_ID = g.GEOGRAPHY_ID
LEFT JOIN ATOMIC.MARKETPLACE_SUPPLIER_RISK msr ON s.SUPPLIER_ID = msr.SUPPLIER_ID AND msr.IS_CURRENT_FLAG = TRUE
LEFT JOIN (
    SELECT 
        SUPPLIER_ID,
        SUM(TOTAL_PURCHASE_ORDER_VALUE) AS TOTAL_SPEND,
        COUNT(DISTINCT PURCHASE_ORDER_ID) AS PO_COUNT
    FROM ATOMIC.PURCHASE_ORDER
    WHERE IS_CURRENT_FLAG = TRUE
    GROUP BY SUPPLIER_ID
) spend ON s.SUPPLIER_ID = spend.SUPPLIER_ID
WHERE s.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- V_SHOULD_COST_ANALYSIS - Contract Price vs Market Index
-- Uses ROW_NUMBER() window function to get closest market index (avoids LATERAL)
-- =============================================================================
CREATE OR REPLACE VIEW V_SHOULD_COST_ANALYSIS AS
SELECT 
    pol.PURCHASE_ORDER_LINE_ID,
    po.PURCHASE_ORDER_NUMBER,
    po.PURCHASE_ORDER_DATE,
    po.ERP_SOURCE_SYSTEM,
    s.SUPPLIER_CODE,
    p.PARTY_NAME AS SUPPLIER_NAME,
    prod.PRODUCT_CODE,
    prod.PRODUCT_NAME,
    pc.CATEGORY_NAME AS MATERIAL_CATEGORY,
    pol.ORDERED_QUANTITY,
    pol.UNIT_PRICE AS CONTRACT_UNIT_PRICE,
    pol.EXTENDED_PRICE AS CONTRACT_TOTAL,
    cur.CURRENCY_CODE,
    -- Get closest market index
    market_price.COMMODITY_TYPE,
    market_price.INDEX_VALUE AS MARKET_INDEX_PRICE,
    market_price.INDEX_DATE AS MARKET_PRICE_DATE,
    -- Calculate variance
    pol.UNIT_PRICE - market_price.INDEX_VALUE AS PRICE_VARIANCE,
    CASE 
        WHEN market_price.INDEX_VALUE > 0 
        THEN ROUND(((pol.UNIT_PRICE - market_price.INDEX_VALUE) / market_price.INDEX_VALUE) * 100, 2)
        ELSE 0 
    END AS PRICE_VARIANCE_PCT,
    -- Calculate potential savings
    CASE 
        WHEN pol.UNIT_PRICE > market_price.INDEX_VALUE 
        THEN (pol.UNIT_PRICE - market_price.INDEX_VALUE) * pol.ORDERED_QUANTITY
        ELSE 0 
    END AS POTENTIAL_SAVINGS,
    -- Should-cost recommendation
    CASE 
        WHEN pol.UNIT_PRICE > market_price.INDEX_VALUE * 1.15 THEN 'RENEGOTIATE'
        WHEN pol.UNIT_PRICE > market_price.INDEX_VALUE * 1.05 THEN 'REVIEW'
        WHEN pol.UNIT_PRICE < market_price.INDEX_VALUE * 0.95 THEN 'FAVORABLE'
        ELSE 'MARKET_RATE'
    END AS SHOULD_COST_RECOMMENDATION
FROM ATOMIC.PURCHASE_ORDER po
JOIN ATOMIC.PURCHASE_ORDER_LINE pol ON po.PURCHASE_ORDER_ID = pol.PURCHASE_ORDER_ID
JOIN ATOMIC.SUPPLIER s ON po.SUPPLIER_ID = s.SUPPLIER_ID
JOIN ATOMIC.PARTY p ON s.PARTY_ID = p.PARTY_ID
LEFT JOIN ATOMIC.PRODUCT prod ON pol.PRODUCT_ID = prod.PRODUCT_ID
LEFT JOIN ATOMIC.PRODUCT_CATEGORY pc ON prod.PRODUCT_CATEGORY_ID = pc.PRODUCT_CATEGORY_ID
LEFT JOIN ATOMIC.CURRENCY cur ON po.CURRENCY_ID = cur.CURRENCY_ID
-- Join to closest market index using ROW_NUMBER() approach
LEFT JOIN (
    SELECT 
        pol2.PURCHASE_ORDER_LINE_ID,
        mci.COMMODITY_TYPE,
        mci.INDEX_VALUE,
        mci.INDEX_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY pol2.PURCHASE_ORDER_LINE_ID 
            ORDER BY mci.INDEX_DATE DESC
        ) AS rn
    FROM ATOMIC.PURCHASE_ORDER_LINE pol2
    JOIN ATOMIC.PURCHASE_ORDER po2 ON pol2.PURCHASE_ORDER_ID = po2.PURCHASE_ORDER_ID
    JOIN ATOMIC.PRODUCT prod2 ON pol2.PRODUCT_ID = prod2.PRODUCT_ID
    JOIN ATOMIC.PRODUCT_CATEGORY pc2 ON prod2.PRODUCT_CATEGORY_ID = pc2.PRODUCT_CATEGORY_ID
    JOIN ATOMIC.MARKETPLACE_COMMODITY_INDEX mci 
        ON mci.COMMODITY_TYPE = pc2.CATEGORY_NAME
        AND mci.INDEX_DATE <= po2.PURCHASE_ORDER_DATE
    WHERE po2.IS_CURRENT_FLAG = TRUE
) market_price ON pol.PURCHASE_ORDER_LINE_ID = market_price.PURCHASE_ORDER_LINE_ID 
    AND market_price.rn = 1
WHERE po.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- V_SUPPLIER_PERFORMANCE_SUMMARY - Aggregated supplier KPIs
-- =============================================================================
CREATE OR REPLACE VIEW V_SUPPLIER_PERFORMANCE_SUMMARY AS
SELECT 
    s.SUPPLIER_ID,
    s.SUPPLIER_CODE,
    p.PARTY_NAME AS SUPPLIER_NAME,
    s.SUPPLIER_TYPE,
    -- On-Time Delivery Rate
    COALESCE(MAX(CASE WHEN sp.METRIC_TYPE = 'ON_TIME_DELIVERY' THEN sp.METRIC_VALUE END), 0) AS ON_TIME_DELIVERY_RATE,
    -- Quality Rate  
    COALESCE(MAX(CASE WHEN sp.METRIC_TYPE = 'QUALITY_ACCEPTANCE' THEN sp.METRIC_VALUE END), 0) AS QUALITY_RATE,
    -- Price Variance
    COALESCE(MAX(CASE WHEN sp.METRIC_TYPE = 'PRICE_VARIANCE' THEN sp.METRIC_VALUE END), 0) AS AVG_PRICE_VARIANCE,
    -- Lead Time Performance
    COALESCE(MAX(CASE WHEN sp.METRIC_TYPE = 'LEAD_TIME_ADHERENCE' THEN sp.METRIC_VALUE END), 0) AS LEAD_TIME_ADHERENCE,
    -- Overall Rating
    COALESCE(MAX(CASE WHEN sp.METRIC_TYPE = 'OVERALL_SCORE' THEN sp.RATING END), 'NOT_RATED') AS OVERALL_RATING,
    -- Latest evaluation period
    MAX(sp.EVALUATION_PERIOD) AS LATEST_EVALUATION_PERIOD
FROM ATOMIC.SUPPLIER s
JOIN ATOMIC.PARTY p ON s.PARTY_ID = p.PARTY_ID
LEFT JOIN ATOMIC.SUPPLIER_PERFORMANCE sp ON s.SUPPLIER_ID = sp.SUPPLIER_ID
WHERE s.IS_CURRENT_FLAG = TRUE
GROUP BY s.SUPPLIER_ID, s.SUPPLIER_CODE, p.PARTY_NAME, s.SUPPLIER_TYPE;

-- =============================================================================
-- V_ESG_SUMMARY - ESG/Sustainability metrics
-- =============================================================================
CREATE OR REPLACE VIEW V_ESG_SUMMARY AS
SELECT 
    s.SUPPLIER_ID,
    s.SUPPLIER_CODE,
    p.PARTY_NAME AS SUPPLIER_NAME,
    pa.COUNTRY AS SUPPLIER_COUNTRY,
    g.GEOGRAPHY_NAME AS REGION,
    msr.ESG_SCORE,
    msr.ENVIRONMENTAL_SCORE,
    msr.SOCIAL_SCORE,
    msr.GOVERNANCE_SCORE,
    -- Supplier emissions (Scope 3)
    COALESCE(em.TOTAL_EMISSIONS, 0) AS SUPPLIER_TOTAL_EMISSIONS_MT,
    -- Spend-weighted ESG
    COALESCE(spend.TOTAL_SPEND, 0) AS TOTAL_SPEND,
    CASE 
        WHEN spend.TOTAL_SPEND > 0 AND msr.ESG_SCORE IS NOT NULL
        THEN msr.ESG_SCORE * spend.TOTAL_SPEND
        ELSE 0
    END AS SPEND_WEIGHTED_ESG,
    -- ESG Risk Level
    CASE 
        WHEN msr.ESG_SCORE < 30 THEN 'HIGH_RISK'
        WHEN msr.ESG_SCORE < 50 THEN 'MEDIUM_RISK'
        WHEN msr.ESG_SCORE < 70 THEN 'LOW_RISK'
        ELSE 'LEADER'
    END AS ESG_RISK_LEVEL
FROM ATOMIC.SUPPLIER s
JOIN ATOMIC.PARTY p ON s.PARTY_ID = p.PARTY_ID
LEFT JOIN ATOMIC.PARTY_ADDRESS pa ON p.PARTY_ID = pa.PARTY_ID AND pa.PRIMARY_ADDRESS_FLAG = TRUE
LEFT JOIN ATOMIC.GEOGRAPHY g ON pa.GEOGRAPHY_ID = g.GEOGRAPHY_ID
LEFT JOIN ATOMIC.MARKETPLACE_SUPPLIER_RISK msr ON s.SUPPLIER_ID = msr.SUPPLIER_ID AND msr.IS_CURRENT_FLAG = TRUE
LEFT JOIN (
    SELECT 
        SUPPLIER_ID,
        SUM(EMISSION_QUANTITY) AS TOTAL_EMISSIONS
    FROM ATOMIC.EMISSION_RECORD
    WHERE POLLUTANT_NAME = 'CO2'
    GROUP BY SUPPLIER_ID
) em ON s.SUPPLIER_ID = em.SUPPLIER_ID
LEFT JOIN (
    SELECT 
        SUPPLIER_ID,
        SUM(TOTAL_PURCHASE_ORDER_VALUE) AS TOTAL_SPEND
    FROM ATOMIC.PURCHASE_ORDER
    WHERE IS_CURRENT_FLAG = TRUE
    GROUP BY SUPPLIER_ID
) spend ON s.SUPPLIER_ID = spend.SUPPLIER_ID
WHERE s.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- V_DEMAND_FORECAST_ANALYSIS - Forecast vs Actuals (from DEMAND_FORECAST table)
-- =============================================================================
CREATE OR REPLACE VIEW V_DEMAND_FORECAST_ANALYSIS AS
SELECT 
    df.DEMAND_FORECAST_ID,
    df.PRODUCT_ID,
    prod.PRODUCT_CODE,
    prod.PRODUCT_NAME,
    pc.CATEGORY_NAME AS MATERIAL_CATEGORY,
    df.SITE_ID,
    site.SITE_NAME,
    site.COUNTRY AS SITE_COUNTRY,
    df.FORECAST_DATE,
    df.FORECAST_QUANTITY,
    df.FORECAST_METHOD,
    df.CONFIDENCE_LEVEL,
    COALESCE(da.ACTUAL_QUANTITY, 0) AS ACTUAL_QUANTITY,
    df.FORECAST_QUANTITY - COALESCE(da.ACTUAL_QUANTITY, 0) AS FORECAST_ERROR,
    CASE 
        WHEN df.FORECAST_QUANTITY > 0 
        THEN ABS(df.FORECAST_QUANTITY - COALESCE(da.ACTUAL_QUANTITY, 0)) / df.FORECAST_QUANTITY * 100
        ELSE 0 
    END AS FORECAST_ERROR_PCT
FROM ATOMIC.DEMAND_FORECAST df
LEFT JOIN ATOMIC.PRODUCT prod ON df.PRODUCT_ID = prod.PRODUCT_ID
LEFT JOIN ATOMIC.PRODUCT_CATEGORY pc ON prod.PRODUCT_CATEGORY_ID = pc.PRODUCT_CATEGORY_ID
LEFT JOIN ATOMIC.SITE site ON df.SITE_ID = site.SITE_ID
LEFT JOIN ATOMIC.DEMAND_ACTUAL da ON df.PRODUCT_ID = da.PRODUCT_ID 
    AND df.SITE_ID = da.SITE_ID 
    AND df.FORECAST_DATE = da.DEMAND_DATE
WHERE df.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- V_DEMAND_FORECAST_PREDICTIONS - ML Model Predictions with enriched data
-- =============================================================================
CREATE OR REPLACE VIEW V_DEMAND_FORECAST_PREDICTIONS AS
SELECT 
    dfp.PRODUCT_ID,
    prod.PRODUCT_CODE,
    pc.CATEGORY_NAME AS MATERIAL_CATEGORY,
    dfp.SITE_ID,
    dfp.PREDICTION_DATE AS FORECAST_DATE,
    dfp.FORECASTED_MATERIAL_DEMAND_QTY AS FORECASTED_DEMAND_QTY,
    da.ACTUAL_QUANTITY AS ACTUAL_DEMAND_QTY,
    dfp.PREDICTION_LOWER_BOUND AS LOWER_BOUND,
    dfp.PREDICTION_UPPER_BOUND AS UPPER_BOUND,
    dfp.CONFIDENCE_LEVEL AS PREDICTION_CONFIDENCE,
    dfp.MODEL_VERSION,
    dfp.CREATED_TIMESTAMP
FROM ATOMIC.DEMAND_FORECAST_PREDICTIONS dfp
LEFT JOIN ATOMIC.PRODUCT prod ON dfp.PRODUCT_ID = prod.PRODUCT_ID
LEFT JOIN ATOMIC.PRODUCT_CATEGORY pc ON prod.PRODUCT_CATEGORY_ID = pc.PRODUCT_CATEGORY_ID
LEFT JOIN ATOMIC.DEMAND_ACTUAL da 
    ON dfp.PRODUCT_ID = da.PRODUCT_ID 
    AND dfp.SITE_ID = da.SITE_ID 
    AND dfp.PREDICTION_DATE = da.DEMAND_DATE;

-- =============================================================================
-- V_EXECUTIVE_KPIs - High-level KPIs for Executive Dashboard
-- =============================================================================
CREATE OR REPLACE VIEW V_EXECUTIVE_KPIS AS
SELECT 
    -- Total Spend
    (SELECT SUM(TOTAL_PURCHASE_ORDER_VALUE) FROM ATOMIC.PURCHASE_ORDER WHERE IS_CURRENT_FLAG = TRUE) AS TOTAL_SPEND,
    -- Supplier Count
    (SELECT COUNT(DISTINCT SUPPLIER_ID) FROM ATOMIC.SUPPLIER WHERE IS_CURRENT_FLAG = TRUE) AS TOTAL_SUPPLIERS,
    -- Active PO Count
    (SELECT COUNT(*) FROM ATOMIC.PURCHASE_ORDER WHERE IS_CURRENT_FLAG = TRUE AND PURCHASE_ORDER_STATUS = 'OPEN') AS ACTIVE_POS,
    -- Risk Exposure (suppliers with financial health < 50)
    (SELECT SUM(COALESCE(spend.TOTAL_SPEND, 0))
     FROM ATOMIC.MARKETPLACE_SUPPLIER_RISK msr
     LEFT JOIN (
         SELECT SUPPLIER_ID, SUM(TOTAL_PURCHASE_ORDER_VALUE) AS TOTAL_SPEND
         FROM ATOMIC.PURCHASE_ORDER WHERE IS_CURRENT_FLAG = TRUE
         GROUP BY SUPPLIER_ID
     ) spend ON msr.SUPPLIER_ID = spend.SUPPLIER_ID
     WHERE msr.IS_CURRENT_FLAG = TRUE AND msr.FINANCIAL_HEALTH_SCORE < 50
    ) AS RISK_EXPOSURE_AMOUNT,
    -- High Risk Supplier Count
    (SELECT COUNT(*) FROM ATOMIC.MARKETPLACE_SUPPLIER_RISK WHERE IS_CURRENT_FLAG = TRUE AND FINANCIAL_HEALTH_SCORE < 50) AS HIGH_RISK_SUPPLIER_COUNT,
    -- Average ESG Score
    (SELECT AVG(ESG_SCORE) FROM ATOMIC.MARKETPLACE_SUPPLIER_RISK WHERE IS_CURRENT_FLAG = TRUE AND ESG_SCORE IS NOT NULL) AS AVG_ESG_SCORE,
    -- Total Carbon Footprint (MT)
    (SELECT SUM(EMISSION_QUANTITY) FROM ATOMIC.EMISSION_RECORD WHERE POLLUTANT_NAME = 'CO2') AS TOTAL_CARBON_FOOTPRINT_MT,
    -- ERP Source Count (simulating 50+ ERPs)
    (SELECT COUNT(DISTINCT ERP_SOURCE_SYSTEM) FROM ATOMIC.PURCHASE_ORDER WHERE IS_CURRENT_FLAG = TRUE) AS ERP_SOURCE_COUNT;

-- Success message
SELECT 'PROCUREMENT_MART views created successfully' AS status;
