-- =============================================================================
-- Snowcore Industries Intelligent Sourcing Hub
-- 07_load_data.sql - Load synthetic data from CSV files
-- =============================================================================

USE DATABASE SNOWCORE_PROCUREMENT;

-- =============================================================================
-- Upload files to stage (run from deploy.sh with PUT commands)
-- This script assumes files have been PUT to @RAW.DATA_STAGE
-- =============================================================================

-- Load CURRENCY
COPY INTO ATOMIC.CURRENCY
FROM @RAW.DATA_STAGE/currency.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load UNIT_OF_MEASURE
COPY INTO ATOMIC.UNIT_OF_MEASURE
FROM @RAW.DATA_STAGE/unit_of_measure.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load GEOGRAPHY
COPY INTO ATOMIC.GEOGRAPHY
FROM @RAW.DATA_STAGE/geography.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PARTY
COPY INTO ATOMIC.PARTY
FROM @RAW.DATA_STAGE/party.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PARTY_ADDRESS
COPY INTO ATOMIC.PARTY_ADDRESS
FROM @RAW.DATA_STAGE/party_address.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load ORGANIZATION
COPY INTO ATOMIC.ORGANIZATION
FROM @RAW.DATA_STAGE/organization.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SITE
COPY INTO ATOMIC.SITE
FROM @RAW.DATA_STAGE/site.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load LOCATION
COPY INTO ATOMIC.LOCATION
FROM @RAW.DATA_STAGE/location.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PRODUCT_CATEGORY
COPY INTO ATOMIC.PRODUCT_CATEGORY
FROM @RAW.DATA_STAGE/product_category.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PRODUCT
COPY INTO ATOMIC.PRODUCT
FROM @RAW.DATA_STAGE/product.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PERSON
COPY INTO ATOMIC.PERSON
FROM @RAW.DATA_STAGE/person.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER
COPY INTO ATOMIC.SUPPLIER
FROM @RAW.DATA_STAGE/supplier.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER_SITE
COPY INTO ATOMIC.SUPPLIER_SITE
FROM @RAW.DATA_STAGE/supplier_site.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER_PRODUCT
COPY INTO ATOMIC.SUPPLIER_PRODUCT
FROM @RAW.DATA_STAGE/supplier_product.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER_PERFORMANCE
COPY INTO ATOMIC.SUPPLIER_PERFORMANCE
FROM @RAW.DATA_STAGE/supplier_performance.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PURCHASE_ORDER
COPY INTO ATOMIC.PURCHASE_ORDER
FROM @RAW.DATA_STAGE/purchase_order.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PURCHASE_ORDER_LINE
COPY INTO ATOMIC.PURCHASE_ORDER_LINE
FROM @RAW.DATA_STAGE/purchase_order_line.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load MARKETPLACE_COMMODITY_INDEX
COPY INTO ATOMIC.MARKETPLACE_COMMODITY_INDEX
FROM @RAW.DATA_STAGE/marketplace_commodity_index.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load MARKETPLACE_SUPPLIER_RISK
COPY INTO ATOMIC.MARKETPLACE_SUPPLIER_RISK
FROM @RAW.DATA_STAGE/marketplace_supplier_risk.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER_DOCUMENT
COPY INTO ATOMIC.SUPPLIER_DOCUMENT
FROM @RAW.DATA_STAGE/supplier_document.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load EMISSION_RECORD
COPY INTO ATOMIC.EMISSION_RECORD
FROM @RAW.DATA_STAGE/emission_record.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load DEMAND_ACTUAL
COPY INTO ATOMIC.DEMAND_ACTUAL
FROM @RAW.DATA_STAGE/demand_actual.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PRODUCT_COST
COPY INTO ATOMIC.PRODUCT_COST
FROM @RAW.DATA_STAGE/product_cost.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load INVENTORY_BALANCE
COPY INTO ATOMIC.INVENTORY_BALANCE
FROM @RAW.DATA_STAGE/inventory_balance.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- =============================================================================
-- PERSONA-SPECIFIC DATA
-- =============================================================================

-- CPO Persona Tables

-- Load DELIVERY_PERFORMANCE (OTIF tracking)
COPY INTO ATOMIC.DELIVERY_PERFORMANCE
FROM @RAW.DATA_STAGE/delivery_performance.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load PROCUREMENT_OPERATIONAL_METRICS
COPY INTO ATOMIC.PROCUREMENT_OPERATIONAL_METRICS
FROM @RAW.DATA_STAGE/procurement_operational_metrics.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load EMISSION_RECORD_SCOPED (Scope 1/2/3)
COPY INTO ATOMIC.EMISSION_RECORD_SCOPED
FROM @RAW.DATA_STAGE/scope_emissions.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER_DIVERSITY
COPY INTO ATOMIC.SUPPLIER_DIVERSITY
FROM @RAW.DATA_STAGE/supplier_diversity.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Category Manager Persona Tables

-- Load FORWARD_CONTRACT
COPY INTO ATOMIC.FORWARD_CONTRACT
FROM @RAW.DATA_STAGE/forward_contract.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load SUPPLIER_SCORECARD
COPY INTO ATOMIC.SUPPLIER_SCORECARD
FROM @RAW.DATA_STAGE/supplier_scorecard.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Data Scientist Persona Tables

-- Load MARKETPLACE_INDICATORS
COPY INTO ATOMIC.MARKETPLACE_INDICATORS
FROM @RAW.DATA_STAGE/marketplace_indicators.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- Load MODEL_REGISTRY
COPY INTO ATOMIC.MODEL_REGISTRY
FROM @RAW.DATA_STAGE/model_registry.csv
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

-- =============================================================================
-- Verify data load
-- =============================================================================
SELECT 'Data load summary:' AS status;

SELECT 'CURRENCY' AS table_name, COUNT(*) AS row_count FROM ATOMIC.CURRENCY
UNION ALL SELECT 'UNIT_OF_MEASURE', COUNT(*) FROM ATOMIC.UNIT_OF_MEASURE
UNION ALL SELECT 'GEOGRAPHY', COUNT(*) FROM ATOMIC.GEOGRAPHY
UNION ALL SELECT 'PARTY', COUNT(*) FROM ATOMIC.PARTY
UNION ALL SELECT 'PARTY_ADDRESS', COUNT(*) FROM ATOMIC.PARTY_ADDRESS
UNION ALL SELECT 'ORGANIZATION', COUNT(*) FROM ATOMIC.ORGANIZATION
UNION ALL SELECT 'SITE', COUNT(*) FROM ATOMIC.SITE
UNION ALL SELECT 'PRODUCT_CATEGORY', COUNT(*) FROM ATOMIC.PRODUCT_CATEGORY
UNION ALL SELECT 'PRODUCT', COUNT(*) FROM ATOMIC.PRODUCT
UNION ALL SELECT 'SUPPLIER', COUNT(*) FROM ATOMIC.SUPPLIER
UNION ALL SELECT 'SUPPLIER_SITE', COUNT(*) FROM ATOMIC.SUPPLIER_SITE
UNION ALL SELECT 'PURCHASE_ORDER', COUNT(*) FROM ATOMIC.PURCHASE_ORDER
UNION ALL SELECT 'PURCHASE_ORDER_LINE', COUNT(*) FROM ATOMIC.PURCHASE_ORDER_LINE
UNION ALL SELECT 'MARKETPLACE_SUPPLIER_RISK', COUNT(*) FROM ATOMIC.MARKETPLACE_SUPPLIER_RISK
UNION ALL SELECT 'MARKETPLACE_COMMODITY_INDEX', COUNT(*) FROM ATOMIC.MARKETPLACE_COMMODITY_INDEX
UNION ALL SELECT 'SUPPLIER_DOCUMENT', COUNT(*) FROM ATOMIC.SUPPLIER_DOCUMENT
-- Persona-specific tables
UNION ALL SELECT 'DELIVERY_PERFORMANCE', COUNT(*) FROM ATOMIC.DELIVERY_PERFORMANCE
UNION ALL SELECT 'PROCUREMENT_OPERATIONAL_METRICS', COUNT(*) FROM ATOMIC.PROCUREMENT_OPERATIONAL_METRICS
UNION ALL SELECT 'EMISSION_RECORD_SCOPED', COUNT(*) FROM ATOMIC.EMISSION_RECORD_SCOPED
UNION ALL SELECT 'SUPPLIER_DIVERSITY', COUNT(*) FROM ATOMIC.SUPPLIER_DIVERSITY
UNION ALL SELECT 'FORWARD_CONTRACT', COUNT(*) FROM ATOMIC.FORWARD_CONTRACT
UNION ALL SELECT 'SUPPLIER_SCORECARD', COUNT(*) FROM ATOMIC.SUPPLIER_SCORECARD
UNION ALL SELECT 'MARKETPLACE_INDICATORS', COUNT(*) FROM ATOMIC.MARKETPLACE_INDICATORS
UNION ALL SELECT 'MODEL_REGISTRY', COUNT(*) FROM ATOMIC.MODEL_REGISTRY
ORDER BY table_name;
